serviceBinaries:
  openmeeting-api: 1
  openmeeting-admin-api: 1
  openmeeting-rpc-user: 1
  openmeeting-rpc-meeting: 1
toolBinaries:
  - check-free-memory
  - check-component
maxFileDescriptors: 10000
