# URI for database connection, leave empty if using address and credential settings directly
uri: ''
# List of MongoDB server addresses
address: [ localhost:27017 ]
# Name of the database
database: openmeeting_v1
# Username for database authentication
username: ""
# Password for database authentication
password: ""
# Maximum number of connections in the connection pool
maxPoolSize: 100
# Maximum number of retry attempts for a failed database connection
maxRetry: 10
